"use client";

import { useState } from "react";

import { reportHistory } from "../data/mock-reports";
import { ReportStatusBadge } from "./report-status-badge";
import { ReportsEmptyState } from "./reports-empty-state";

import { Pagination } from "../../../components/ui/pagination";

export function ReportsTable() {
    if (!reportHistory.length) {
        return <ReportsEmptyState />;
    }

    const [currentPage, setCurrentPage] =
        useState(1);

    const ITEMS_PER_PAGE = 5;

    const filteredReports =
        reportHistory;

    const totalPages = Math.ceil(
        filteredReports.length /
        ITEMS_PER_PAGE
    );

    const paginatedReports =
        filteredReports.slice(
            (currentPage - 1) *
            ITEMS_PER_PAGE,
            currentPage *
            ITEMS_PER_PAGE
        );

    return (
        <div
            className="
            rounded-2xl
            border
            border-slate-800
            bg-slate-900/40
            p-6
            "
        >
            <div className="mb-6">
                <h3 className="text-lg font-semibold text-white">
                    Report History
                </h3>

                <p className="text-sm text-slate-400">
                    Previously generated reports.
                </p>
            </div>

            <div className="overflow-x-auto">
                <table className="w-full min-w-[800px]">
                    <thead>
                        <tr className="border-b border-slate-800">
                            <th className="pb-4 text-left text-slate-400">
                                Report ID
                            </th>

                            <th className="pb-4 text-left text-slate-400">
                                Type
                            </th>

                            <th className="pb-4 text-left text-slate-400">
                                Generated At
                            </th>

                            <th className="pb-4 text-left text-slate-400">
                                Generated By
                            </th>

                            <th className="pb-4 text-left text-slate-400">
                                Format
                            </th>

                            <th className="pb-4 text-left text-slate-400">
                                Status
                            </th>
                        </tr>
                    </thead>

                    <tbody>
                        {paginatedReports.map(
                            (report) => (
                                <tr
                                    key={report.id}
                                    className="
                                    border-b
                                    border-slate-800/50
                                    "
                                >
                                    <td className="py-4 text-white">
                                        {report.id}
                                    </td>

                                    <td className="py-4 text-slate-300">
                                        {report.reportType}
                                    </td>

                                    <td className="py-4 text-slate-300">
                                        {report.generatedAt}
                                    </td>

                                    <td className="py-4 text-slate-300">
                                        {report.generatedBy}
                                    </td>

                                    <td className="py-4 text-slate-300">
                                        {report.format}
                                    </td>

                                    <td className="py-4">
                                        <ReportStatusBadge
                                            status={
                                                report.status
                                            }
                                        />
                                    </td>
                                </tr>
                            )
                        )}
                    </tbody>
                </table>
            </div>

            {totalPages > 1 && (
                <div className="mt-6">
                    <Pagination
                        currentPage={
                            currentPage
                        }
                        totalPages={
                            totalPages
                        }
                        onPageChange={
                            setCurrentPage
                        }
                    />
                </div>
            )}
        </div>
    );
}