"use client";

import { useMemo, useState } from "react";

import { Pagination } from "../../../components/ui/pagination";
import { AppButton } from "../../../components/ui/app-button";

import { mockInventoryReports } from "../data/mock-inventory-reports";

import { InventoryExportModal } from "./inventory-export-modal";

export function InventoryReportTable() {
    const [search, setSearch] =
        useState("");

    const [currentPage, setCurrentPage] =
        useState(1);

    const [openExport, setOpenExport] =
        useState(false);

    const ITEMS_PER_PAGE = 5;

    const filteredReports =
        useMemo(() => {
            return mockInventoryReports.filter(
                (report) =>
                    report.reportType
                        .toLowerCase()
                        .includes(
                            search.toLowerCase()
                        )
            );
        }, [search]);

    const totalPages = Math.ceil(
        filteredReports.length /
        ITEMS_PER_PAGE
    );

    const paginatedReports =
        filteredReports.slice(
            (currentPage - 1) *
            ITEMS_PER_PAGE,
            currentPage *
            ITEMS_PER_PAGE
        );

    return (
        <div
            className="
            rounded-2xl
            border border-slate-800
            bg-slate-900/40
            p-6
            "
        >
            <div className="mb-6 flex items-center justify-between">
                <input
                    value={search}
                    onChange={(e) =>
                        setSearch(
                            e.target.value
                        )
                    }
                    placeholder="Search reports..."
                    className="
                    h-11
                    w-80
                    rounded-xl
                    border border-slate-800
                    bg-slate-950
                    px-4
                    text-white
                    "
                />

                <AppButton
                    onClick={() =>
                        setOpenExport(true)
                    }
                >
                    Export Report
                </AppButton>
            </div>

            <table className="w-full">
                <thead>
                    <tr className="border-b border-slate-800">
                        <th className="pb-4 text-left text-slate-400">
                            Report ID
                        </th>

                        <th className="pb-4 text-left text-slate-400">
                            Type
                        </th>

                        <th className="pb-4 text-left text-slate-400">
                            Date
                        </th>

                        <th className="pb-4 text-left text-slate-400">
                            Generated By
                        </th>

                        <th className="pb-4 text-left text-slate-400">
                            Format
                        </th>

                        <th className="pb-4 text-left text-slate-400">
                            Status
                        </th>
                    </tr>
                </thead>

                <tbody>
                    {paginatedReports.map(
                        (report) => (
                            <tr
                                key={
                                    report.id
                                }
                                className="border-b border-slate-800/50"
                            >
                                <td className="py-4 text-white">
                                    {report.id}
                                </td>

                                <td className="py-4 text-slate-300">
                                    {
                                        report.reportType
                                    }
                                </td>

                                <td className="py-4 text-slate-300">
                                    {
                                        report.generatedAt
                                    }
                                </td>

                                <td className="py-4 text-slate-300">
                                    {
                                        report.generatedBy
                                    }
                                </td>

                                <td className="py-4 text-slate-300">
                                    {
                                        report.format
                                    }
                                </td>

                                <td className="py-4">
                                    <span
                                        className={`
                                        rounded-full
                                        px-3
                                        py-1
                                        text-xs
                                        ${report.status ===
                                                "Completed"
                                                ? "bg-green-500/10 text-green-400"
                                                : "bg-yellow-500/10 text-yellow-400"
                                            }
                                        `}
                                    >
                                        {
                                            report.status
                                        }
                                    </span>
                                </td>
                            </tr>
                        )
                    )}
                </tbody>
            </table>

            {totalPages > 1 && (
                <div className="mt-6">
                    <Pagination
                        currentPage={
                            currentPage
                        }
                        totalPages={
                            totalPages
                        }
                        onPageChange={
                            setCurrentPage
                        }
                    />
                </div>
            )}

            <InventoryExportModal
                open={openExport}
                onClose={() =>
                    setOpenExport(false)
                }
            />
        </div>
    );
}